image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - echo "Running build command..."
    - npm run build
    - echo "Current working directory:"
    - pwd
    - echo "Listing contents of the build directory:"
    - ls -la build
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  only:
    - main

pages:
  stage: deploy
  script:
    - echo "Copying build files to the public directory..."
    - mkdir -p public
    - cp -r build/* public/
    - echo "Listing contents of the public directory:"
    - ls -la public
  artifacts:
    paths:
      - public
  only:
    - main
