image: node:14

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
    - echo "Contents of build directory:"
    - ls -la build/  # Debugging: List files in the build directory
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  only:
    - main

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r build/* .public/  # Copy build contents to .public
    - echo "Contents of .public directory:"
    - ls -la .public/  # Debugging: List files in the .public directory
  artifacts:
    paths:
      - .public
  only:
    - main
