image: mcr.microsoft.com/windows/nanoserver:1809

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - echo "Running build command..."
    - npm run build
    - echo "Current working directory:"
    - pwd
    - echo "Listing contents of the build directory:"
    - Get-ChildItem -Path build -Force
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  only:
    - main

pages:
  stage: deploy
  script:
    - echo "Creating .public directory..."
    - New-Item -Path .public -ItemType Directory -Force
    - echo "Copying files to .public directory..."
    - Copy-Item -Path build\* -Destination .public\ -Recurse
    - echo "Listing contents of .public directory:"
    - Get-ChildItem -Path .public -Force
  artifacts:
    paths:
      - .public
  only:
    - main
